- name: Get the personal certificates
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.ssl_certificates.personal_certificate.get_all
    isamapi:
      kdb_id: "{{ get_personal_certificates_kdb_id }}"
  register: ret_obj

- name: set a fact to be used by other components
  set_fact:
    get_personal_certificates_ret_obj: "{{ ret_obj['data'] }}"
