- name: Add a Junction - {{ add_junction_junction_point }}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.junctions.add
    isamapi:
      junction_point:                   "{{ add_junction_junction_point }}"
      junction_type:                    "{{ add_junction_junction_type }}"
      reverseproxy_id:                  "{{ add_junction_reverseproxy_id }}"
      server_hostname:                  "{{ add_junction_server_hostname }}"
      server_port:                      "{{ add_junction_server_port }}"
      basic_auth_mode:                  "{{ add_junction_basic_auth_mode }}"
      stateful_junction:                "{{ add_junction_stateful_junction }}"
      client_ip_http:                   "{{ add_junction_client_ip_http }}"
      scripting_support:                "{{ add_junction_scripting_support }}"
      junction_cookie_javascript_block: "{{ add_junction_junction_cookie_javascript_block }}"
      virtual_hostname:                 "{{ add_junction_virtual_hostname }}"
      server_dn:                        "{{ add_junction_server_dn }}"
      query_contents:                   "{{ add_junction_query_contents }}"
      case_sensitive_url:               "{{ add_junction_case_sensitive_url }}"
      windows_style_url:                "{{ add_junction_windows_style_url }}"
      https_port:                       "{{ add_junction_https_port }}"
      http_port:                        "{{ add_junction_http_port }}"
      proxy_hostname:                   "{{ add_junction_proxy_hostname }}"
      proxy_port:                       "{{ add_junction_proxy_port }}"
      sms_environment:                  "{{ add_junction_sms_environment }}"
      vhost_label:                      "{{ add_junction_vhost_label }}"
      junction_hard_limit:              "{{ add_junction_junction_hard_limit }}"
      junction_soft_limit:              "{{ add_junction_junction_soft_limit }}"
      tfim_sso:                         "{{ add_junction_tfim_sso }}"
      remote_http_header:               "{{ add_junction_remote_http_header }}"
      preserve_cookie:                  "{{ add_junction_preserve_cookie }}"
      cookie_include_path:              "{{ add_junction_cookie_include_path }}"
      transparent_path_junction:        "{{ add_junction_transparent_path_junction }}"
      mutual_auth:                      "{{ add_junction_mutual_auth }}"
      insert_session_cookies:           "{{ add_junction_insert_session_cookies }}"
      request_encoding:                 "{{ add_junction_request_encoding }}"
      enable_basic_auth:                "{{ add_junction_enable_basic_auth }}"
      key_label:                        "{{ add_junction_key_label }}"
      gso_resource_group:               "{{ add_junction_gso_resource_group }}"
      version_two_cookies:              "{{ add_junction_version_two_cookies }}"
      ltpa_keyfile:                     "{{ add_junction_ltpa_keyfile }}"
      authz_rules:                      "{{ add_junction_authz_rules }}"
      fsso_config_file:                 "{{ add_junction_fsso_config_file }}"
      username:                         "{{ add_junction_username }}"
      password:                         "{{ add_junction_password }}"
      server_uuid:                      "{{ add_junction_server_uuid }}"
      local_ip:                         "{{ add_junction_local_ip }}"
      ltpa_keyfile_password:            "{{ add_junction_ltpa_keyfile_password }}"
      delegation_support:               "{{ add_junction_delegation_support }}"
      insert_ltpa_cookies:              "{{ add_junction_insert_ltpa_cookies }}"
      http2_junction:                   "{{ add_junction_http2_junction }}"
      http2_proxy:                      "{{ add_junction_http2_proxy }}"
      sni_name:                         "{{ add_junction_sni_name }}"
  when:
    - add_junction_junction_point is defined
    - add_junction_junction_type is defined
    - add_junction_reverseproxy_id is defined
    - add_junction_server_hostname is defined
    - add_junction_server_port is defined
