---
- name: Get junction servers
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.reverse_proxy.junctions.get
    isamapi:
      reverseproxy_id: "{{ item.0.inst_name }}"
      junctionname: "{{ item.1.junction_point  }}"
  register: ret_obj
- name: Delete junction servers
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.reverse_proxy.junctions_server.delete
    isamapi:
      reverseproxy_id: "{{ item.0.inst_name }}"
      junction_point: "{{ item.1.junction_point }}"
      server_hostname: "{{ server.server_hostname }}"
      server_port: "{{ server.server_port }}"
  vars:
    filter: "[? server_hostname == '{{ server.server_hostname }}' && server_port == `{{ server.server_port }}`]"
  when: (item.1.servers | json_query(filter)) == []
  with_items: "{{ ret_obj | json_query('data.servers[].{server_hostname: server_hostname, server_port: server_port}') }}"
  loop_control:
    loop_var: server
