- name: Update Runtime ldap.conf for Basic User Support
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action    : ibmsecurity.isam.web.runtime.configuration.entry.update
    isamapi:
      resource_id : "{{ item.resource }}"
      stanza_id   : "{{ item.stanza }}"
      entry_id    : "{{ item.entry }}"
      value_id    : "{{ item.value }}"
  with_items:
  - resource : "ldap.conf"
    stanza   : "ldap"
    entry    : "basic-user-support"
    value    : "{{ config_fed_dir_basic_user_support | default('yes') }}"
  - resource : "ldap.conf"
    stanza   : "ldap"
    entry    : "basic-user-pwd-policy"
    value    : "{{ config_fed_dir_basic_user_pwd_policy | default('no') }}"
  notify:
  - Commit Changes
  - Restart Web Runtime
