# Example to add an LDAP group to the Security Administrator management authorization role group
# - name: set management authorization role group
#   include_role:
#     name: set_role_group
#   vars:
#     set_role_group_name: Security Administrator
#     set_role_group_group_name: test_group
#     set_role_group_type: ldap
- name: Add a group to a management authorization role group
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.management_authorization.role_group.set
    isamapi:
      name: "{{ set_role_group_name }}"
      group_name: "{{ set_role_group_group_name }}"
      type: "{{ set_role_group_type }}"
  when: set_role_group_name is defined and set_role_group_group_name is defined
  notify: Commit Changes
