- name: Configure System Alert to Email
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.system_alerts.email.add
    isamapi:
      name : "Email Alert to {{ add_system_alerts_smtpServer }}"
      smtpServer : "{{ add_system_alerts_smtpServer }}"
      smtpPort : "{{ add_system_alerts_smtpPort }}"
      from_email : "{{ add_system_alerts_from_email }}"
      to_email : "{{ add_system_alerts_to_email }}"
      comment : "Email Alert to {{ add_system_alerts_smtpServer }}"
  when: add_system_alerts_smtpServer is defined
  register: alertObj
  notify: Commit Changes


- name: Enable System Alert - Created in previous Step
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.system_alerts.alerts.enable
    isamapi:
      uuid    : "{{ alertObj['data']['uuid'] }}"
      objType : "{{ alertObj['data']['objType'] }}"
  when: add_system_alerts_smtpServer is defined and alertObj.changed and (not ansible_check_mode)
  notify: Commit Changes
