- name: Check if Signature File Exists - {{ add_cluster_node_signature_file }}
  stat:
    path: "{{ add_cluster_node_signature_file }}"
    get_checksum: False
    get_md5: False
  register: signature_file

- name: Add {{ inventory_hostname }} to cluster
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.cluster.node.add
    isamapi:
      signature_file: "{{ add_cluster_node_signature_file }}"
      restricted:     "{{ add_cluster_node_restricted }}"
  when: add_cluster_node_signature_file is defined and signature_file.stat.exists
  notify:
  - Commit Changes

# Commit cluster changes before proceeding
- meta: flush_handlers
