---
# Adding interface with custom isamapi parameters
# Therefore combining label with interface parameter:
# Example: 
#  inventroy:
#    - label:  '1.1'
#      addresses:
#       - address:            "192.168.230.130"
#         maskOrPrefix:       "24"
#         allowManagement:    true
#         enabled:            true
#       - address:            "192.168.230.131"
#         maskOrPrefix:       "24"
#         allowManagement:    false
#         enabled:            true
#  modul transformation:
#   item:
#     - label: '1.1'
#       address:            "192.168.230.130"
#       maskOrPrefix:       "24"
#       allowManagement:    true
#       enabled:            true
#     - label: '1.1'
#       address:            "192.168.230.131"
#       maskOrPrefix:       "24"
#       allowManagement:    false
#       enabled:            true
- name: add interfaces [interfaces]
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    action: "ibmsecurity.isam.base.network.{{ add_interfaces_action }}.add"
    isamapi: "{{ {} | combine(item.0) | combine(item.1) }}"
  with_subelements:
    -   "{{Â interfaces }}"
    -   addresses
  notify: Commit Changes
