---
# task file for ISAM appliance first steps
#
#     accept service agreements
#     set up LMI FIPS
#     change password
#     commit and restart appliance
#
# accept service agreements
- name: Accept Service Agreements
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  admin
    password:  admin
    lmi_port:  "{{ port | default(omit) }}"
    action: ibmsecurity.isam.base.service_agreement.set

# set up LMI FIPS
- name: Setup FIPS Mode
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  admin
    password:  admin
    lmi_port:  "{{ port | default(omit) }}"
    action: ibmsecurity.isam.base.fips.set
    isamapi:
        fipsEnabled: "{{FIPS_cfg.fipsEnabled}}"
        tlsv10Enabled: "{{FIPS_cfg.tlsv10Enabled}}"
        tlsv11Enabled: "{{FIPS_cfg.tlsv11Enabled}}"
  register: ret_obj
  when: FIPS_cfg is defined and FIPS_cfg.fipsEnabled == true and first_steps_fips == true

# Restart after FIPS if needed
- name: Restart after enabling FIPS
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  admin
    password:  admin
    lmi_port:  "{{ port | default(omit) }}"
    action: ibmsecurity.isam.base.fips.restart_and_wait
  when: first_steps_fips and ret_obj.data.reboot is defined and ret_obj.data.reboot == true

# Complete the appliance set up
- name: Complete Appliance Setup
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  admin
    password:  admin
    lmi_port:  "{{ port | default(omit) }}"
    action: ibmsecurity.isam.base.setup_complete.set

# Change password
- name: Change password for admin user
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  admin
    password:  admin
    lmi_port:  "{{ port | default(omit) }}"
    action: ibmsecurity.isam.base.admin.set_pw
    isamapi:
        'oldPassword': 'admin'
        'newPassword': "{{ password }}"
        'sessionTimeout': "{{ lmi_session_timeout }}"
  when: first_steps_admin_pwd == true

# Commit changes and restart LMI
- name: Commit Changes and Restart LMI
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  admin
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    action: ibmsecurity.isam.appliance.commit_and_restart_and_wait
