# There should be just one "id" with value of "1" - this step is avoid hardcoding id
- name: Query Existing Audit Configuration for "id"
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.audit_configuration.get
  register: ret_obj

- name: Set Audit Configuration - id "{{ ret_obj['data'][0]['id'] }}"
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.audit_configuration.set
    isamapi:
      id:      "{{ ret_obj['data'][0]['id'] }}"
      enabled: "{{ set_audit_configuration_enabled }}"
      type:    "{{ set_audit_configuration_type }}"
      config:  "{{ set_audit_configuration_config }}"
      verbose: "{{ set_audit_configuration_verbose }}"
  notify: Commit Changes

