# Update existing stanza(s)/entries in reverse proxy config file
- name: Configure Reverse Proxy stanza(s) entries (Adds)
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.configuration.entry.add
    isamapi:
      reverseproxy_id: "{{ add_reverseproxy_conf_reverseproxy_id }}"
      stanza_id:       "{{ item.stanza_id }}"
      entries:         "{{ item.entries }}"
  with_items:          "{{ add_reverseproxy_conf_entries }}"
  when: add_reverseproxy_conf_entries is defined and add_reverseproxy_conf_reverseproxy_id is defined
  notify:
  - Commit Changes
  - Restart Reverse Proxy
