- name: Create File in Management Root {{ create_mgmt_root_file_name }}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.management_root.file.create
    isamapi:
      instance_id: "{{ create_mgmt_root_file_instance_id }}"
      id         : "{{ create_mgmt_root_file_id }}"
      name       : "{{ create_mgmt_root_file_name }}"
      contents   : "{{ create_mgmt_root_file_contents }}"
  when:
    - create_mgmt_root_file_contents is defined
    - create_mgmt_root_file_name is defined
    - create_mgmt_root_file_instance_id is defined
    - create_mgmt_root_file_id is defined
  notify:
  - Commit Changes
