---
# Adding interface with custom isamapi parameters
# Therefore combining label with interface parameter:
# Example:
#  interfaces:
#    - label:  '1.1'
#      addresses:
#       - address:            "192.168.230.130"
#         maskOrPrefix:       "24"
#         allowManagement:    true
#         enabled:            true
#       - address:            "192.168.230.131"
#         maskOrPrefix:       "24"
#         allowManagement:    false
#         enabled:            true
- name: Add interfaces
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: "ibmsecurity.isam.base.network.{{ add_interfaces_action }}.add"
    isamapi:
      label: "{{ item.0.label }}"
      address: "{{ item.1.address }}"
      maskOrPrefix: "{{ item.1.maskOrPrefix }}"
      allowManagement: "{{ item.1.allowManagement }}"
      enabled: "{{ item.1.enabled | default(False) }}"
  loop:  "{{Â interfaces | subelements('addresses', {'skip_missing': True}) }}"
  loop_control:
    label: "Processing interface {{ item.0.label }} and ip address {{ item.1.address }}"
  notify: Commit Changes
